# Permalinks
permalink:           pretty

# Setup
title:               Nathan Harrington
#tagline:             Programmer
url:                 http://nathanharrington.info
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nathan Harrington
  url:               http://nathanharrington.info
  email:             harrington.nathan@gmail.com

# Custom vars
version:             1.0.0
github:
repo:              http://nathanharrington.github.io/

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

pages_list:       
#    Articles: '/articles/'
#    Projects: '/archive/'
    Resume: '/assets/resume/NathanHarrington_Resume.rtf'
    Github: 'http://github.com/NathanHarrington'
